### ISSUE TITLE
Handy JVM options for tools.deps project

### ISSUE THREAD

**Issue by practicalli-john** [practicalli/blog#32]
How to add JVM options when running Clojure CLI.
Describe common JVM options and when they would be used (option to manage heap size, garbage collection, etc.)

#### Clojure.org references
https://clojure.org/reference/deps_and_cli#_prepare_jvm_environment

#### Clojure CLI command line options
Clojure CLI `-J` flag passes configuration options to the JVM. When there are multiple, each must be prefixed with `-J`.

```
clojure -J--add-modules -Jjava.xml.bind
```

#### Clojure CLI deps.edn configuration
In Clojure CLI deps.edn configuation main execution take a map with key :jvm-opts:

`:jvm-opts` is either a top-level key or alias key, which has a value that is a collection of string JVM options `["--add-modules" "]`

Set a large heap size
```
 :aliases
 {:jvm/heap2g {:jvm-opts ["-Xmx2G"]}}}
```

TODO: what does this do?
```
:aliases {:jvm/xml-bind {:jvm-opts ["–add-modules java.xml.bind"]}}
```

If `-J` JVM options are also specified on the command line, they are concatenated after the alias options

This map is stored in alias data and provided to the Clojure tools using -A (for REPL invocation), -X (for function execution), or -M (for clojure.main execution). Multiple aliases can be provided by concatentating the alias names.

#### Clojure ubjerjar
JVM options must be specified when calling an uberjar with the Java command

```
java -jar project-uberjar.jar -J...
```
TODO: confirm example

#### Cider settings
Slack discussion: https://clojurians.slack.com/archives/C0617A8PQ/p1645530472596039
JVM flags to avoid OOMs, here are mine (for a 64GB MBP) https://github.com/reducecombine/.lein/blob/f01aec663ff4ac8f8e83f8eca93a13b2cf99aa4b/profiles.clj#L10-L43

From Leiningen project.clj file
```
:jvm-opts
[;; Disable all UI features for disabling the clipboard - for personal security:
 "-Djava.awt.headless=true"
 ;; Remove useless icon from the Dock:
 "-Dapple.awt.UIElement=true"
 "-Dclash.dev.expound=true"
 ;; Make more info available to debuggers:
 "-Dclojure.compiler.disable-locals-clearing=true"
 ;; If failing on startup, print stacktraces directly instead of saving them to a file:
 "-Dclojure.main.report=stderr"
 ;; Changes nothing - just to remember how it's done:
 "-Dclojure.spec.skip-macros=false"
 ;; Changes nothing - just to remember how it's done:
 "-Dclojure.spec.compile-asserts=true"
 ;; Enable tiered compilation, for guaranteeing accurate benchmarking (at the cost of slower startup):
 "-XX:+TieredCompilation"
 ;; Don't elide stacktraces:
 "-XX:-OmitStackTraceInFastThrow"
 ;; Prevents a specific type of OOMs:
 "-XX:CompressedClassSpaceSize=3G"
 ;; Prevents trivial StackOverflow errors:
 "-XX:MaxJavaStackTraceDepth=1000000"
 ;; Set a generous limit as the maximum that can be allocated, preventing certain types of OOMs:
 "-Xmx24G"
 ;; increase stack size x6, for preventing SO errors:
 ;;   (The current default can be found with
 ;;    `java -XX:+PrintFlagsFinal -version 2>/dev/null | grep "intx ThreadStackSize"`)
 "-Xss6144k"
 ;; Set a minimum amount of memory that matches/exceeds a given repl's initial usage (including various tooling).
 ;; This way, initial performance improves:
 "-Xms6G"
 ;; Improves startup time:
 "-Xverify:none"
 ;; Enable various optimizations, for guaranteeing accurate benchmarking (at the cost of slower startup):
 "-server"]
```
 Simulate the maximum heap allocation that a process can have when Xmx is left unconfigured:
``` 
:low-mem            {:jvm-opts ["-Xmx1G"]}
```

#### Garbage Collection
Setup GC with short STW pauses which can be relevant for very high web server workloads

Source: https://docs.oracle.com/cd/E40972_01/doc.70/e40973/cnf_jvmgc.htm#autoId2
``` 
:g1gc               {:jvm-opts ["-XX:+UseG1GC"
                                 "-XX:MaxGCPauseMillis=200"
                                 "-XX:ParallelGCThreads=20"
                                 "-XX:ConcGCThreads=5"
                                 "-XX:InitiatingHeapOccupancyPercent=70"]}
```

#### JVM options of a running JVM process 
- use a JMX client
- https://visualvm.github.io/
- `jcmd pid VM.system_properties` or `jcmd pid VM.flags` using `jcmd -l` to get the pid of the JVM process
- on Linux `ps -ef | grep java` which includes the options to run the JVM process, `ps -auxww` to show long arguments

* [Getting the parameters of a running JVM](https://stackoverflow.com/questions/5317152/getting-the-parameters-of-a-running-jvm)

#### References
* [JVM Options cheatsheet - JRebel](https://www.jrebel.com/blog/jvm-options-cheat-sheet)

**Comment by practicalli-johnny** [comment]
Added Clojure CLI JVM options page
* https://practical.li/clojure/reference/clojure-cli/jvm-options.html

Added Java Virtual Machine section
* https://practical.li/clojure/reference/jvm/
